# Generated by Django 3.2 on 2025-07-23 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(default='暂无评论', verbose_name='评论内容')),
                ('area', models.CharField(max_length=100, verbose_name='用户ip')),
                ('gender', models.CharField(max_length=20, verbose_name='性别')),
                ('fans_num', models.IntegerField(verbose_name='粉丝数')),
                ('follow_num', models.IntegerField(verbose_name='关注数')),
                ('pub_num', models.IntegerField(verbose_name='用户发布微博数')),
                ('comment_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='评论时间')),
                ('keyword', models.CharField(max_length=100, verbose_name='评论所属热搜')),
                ('lstm_result', models.CharField(default='未知情感', max_length=100, verbose_name='情感倾向')),
                ('lstm_score', models.CharField(default='0.0', max_length=50, verbose_name='情感得分')),
            ],
            options={
                'verbose_name_plural': '评论管理',
            },
        ),
    ]
