# Generated by Django 3.2 on 2025-07-23 06:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=40, verbose_name='密码')),
                ('ueamil', models.CharField(max_length=30, verbose_name='电子邮箱')),
                ('uaddress', models.CharField(max_length=30, verbose_name='地址')),
                ('uyoubian', models.CharField(max_length=30, verbose_name='邮编')),
                ('uphone', models.CharField(max_length=30, verbose_name='手机号')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('avatar', models.TextField(default='/static/img/default.jpg', verbose_name='头像')),
            ],
            options={
                'verbose_name_plural': '用户管理',
            },
        ),
    ]
